federation_version: 2
subgraphs:
  authors:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  books:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002